### PR TITLE
Add Speedyrails Theme

### PR DESCRIPTION
**Pull request by mbuttler**
- Adds Theme Directory

### CODE REVIEW

**Comment by adamcooke** [comment]
What are these? Can you try to stop opening them? 😄

**Comment by mbuttler** [comment]
I'm really sorry dude, I keep pushing to the wrong repo

**Comment by adamcooke** [comment]
That's OK but each one triggers a few e-mails :(

**Comment by mbuttler** [comment]
Yeah, I'm super embarassed by this. I didn't set the head fork?

**Comment by adamcooke** [comment]
Happens to us all! Well... I've never done it myself. But I'm sure it's easy to do/ 👍

**Pull request closed without merging**
