### PR TITLE
Working docker config

### LINKED ISSUE #19: Improving deployment approach
This looks excellent, and I'd like to use it. I don't particularly want to have to install Ruby and set up and maintain a MySQL DB just to run my status site though.

Any enthusiasm for automating this away? I'm mostly imagining adding a Dockerfile that wraps that setup up, so anybody with Docker set up can just pull the staytus image, start it, and go. Happy to do the legwork to put that in place, but obviously only if it's something you'd consider merging.

Non-docker approaches would work perfectly well too, if you can think of a simple one, but I'm not aware of anything that would work quite as neatly for this.

### PR DESCRIPTION
**Pull request by pimterry**
This fixes #19.

This changes includes a Dockerfile (defining how to build the docker image), and a script that's run by the docker container each time it's started. That script initially generates a DB password and does initial app setup, and then persists the resulting config, and subsequently restores the persisted config, and checks to see if any migrations are required.

This doesn't yet support persisting custom themes you add, but I don't think that'd be too hard, I just haven't got to it yet, and this is a good to start for now.

To test this:
1. Pull this PR down locally
2. Install docker locally
3. Run `docker build .` in the root of the project, to generate the image (this will save the files in the current directory as the initial state for the image)
4. Start a docker container from that image, following the instructions now in the readme, using the hash of the built container instead of `adamcooke/staytus` (which isn't a published image, yet). 

I've only tested this locally, so there might be some teething problems, but give that a go and see what happens. You should end up with a staytus app running on localhost:80.

If that works and you're happy with this, the next step is to create an account on [Docker Hub](https://hub.docker.com/account/signup/) and push the built image to it, so that other people can just reference `adamcooke/staytus` to download and run it.

To keep that up to date you'll need to then publish a new image when you release new versions. You can easily automate that though if you want, to get Docker Hub to automatically build and publish new images everytime you change master. See https://docs.docker.com/docker-hub/builds/.

### CODE REVIEW

**Comment by ApfelUser** [comment]
:+1: Was just searching for this this morning

**Comment by adamcooke** [comment]
Thanks for doing this. I haven't had a moment to try and get docker running on my computer but I'll certainly try and give this a look ASAP

**Comment by pimterry** [comment]
Sure, no hurry. Let me know if I can help at all!

**Comment by pimterry** [comment]
Any update on this?

**Comment by ApfelUser** [comment]
Yeah. Any updates?

**Comment by Savemech** [comment]
And here we are; @adamcooke any chances to get this fancy?

**Comment by adamcooke** [comment]
I've now tested this and it looks good to me (although I couldn't get the port to actually be exposed on my machine).

**Comment by Savemech** [comment]
many thanks!

**Pull request closed without merging**
