### PR TITLE
 #5 Add groups to organize services

### PR DESCRIPTION
**Pull request by novotarq**

### CODE REVIEW

**Comment by adamcooke** [comment]
Thank you for this. I've merged this but I've made a couple of changes to add styles to the headings but also to ensure that themes that don't support groups don't break with this update.

**Comment by kubajaburek** [comment]
Awesome, I was waiting long for this (I can't code in Ruby by myself). You both rock!

**Comment by adamcooke** [comment]
No problem. It's still not in stable yet but everything looks good to me. Let me know if you have any issues with it though.

**Comment by kubajaburek** [comment]
Just finished upgrading, everything's working flawlessly. Big 👍

**Pull request closed without merging**
