### PR TITLE
api: create/update issue, resolves #13

### LINKED ISSUE #13: Api to create/update incidents
are you planning to implement API to create/update incidents.
It would be really useful to have it so that twe can have alert integration with monitoring systems (new alrert, alert resolution, update, etc,...)

### PR DESCRIPTION
**Pull request by glaszig**
this adds api endpoints to post issues and issue updates as requested in #13. it also introduces integration tests.

before merging this i'd like to know what people's workflow is for posting issue updates. this pr requires the api client to know a specific issue id to post updates to. this requires quite some logic and persistence on a client's side which i find quite complicated/frustrating.
in a perfect world, i'd run small and simple agents who just post an issue for a service upon which subscribers get notified. then, when things resolve themselves, the agent just changes the service's status back to operational and subscribers, again, get notified.

what do you think?

### CODE REVIEW

**Comment by adamcooke** [comment]
Thanks for all this.

If you're creating a system which automatically creates issues based on the live status of a service, you would be better simply changing the status of that service rather than maintaining an issue for it. In Staytus, an issue should usually be updated by a human who can provide additional information about the problem. Here's an example of what I think should happening when integrating with external monitoring scripts:

1. Monitoring detects service as offline
2. Updates the status of the service in Staytus using the API
3. Monitoring detects service as available again
4. Updates the status of the service in Staytus using the API

It may be useful to insert a new **Investigating** issue at step 2. Human engineers can then use this as a starting point to provide further updates on the issue and resolve it when appropriate.

As the script will make no further updates to the issue, it doesn't need to keep track of the ID (although, of course, it can if needed). Alternatively, it could look up the ID from a `list` API method.

In the meantime, I'm happy to merge this but there appears to be a conflict at the moment.

**Comment by glaszig** [comment]
makes total sense. thanks.
the only concern left for me is: plain service status changes don't trigger any notification, afaik.

adapting to the workflow you described, it'd be ideal (at least in my case) to receive a notification (e.g. email) when something changes a services status. this will allow anybody interested to know about possible issues and it'll allow me to react to the problem by posting related issues.

what do you think? (this might be another github issue, though)

**Comment by glaszig** [comment]
bump.

**Comment by adamcooke** [comment]
Sorry - I completely missed the original update to this! Should be able to get this merged today :)

**Comment by adamcooke** [comment]
Merged :)

**Comment by nickmisasi13** [comment]
Hi,

I've noticed that the documentation for the API is missing information on this commit. Is there somewhere I can access it?

**Pull request closed without merging**
