### PR TITLE
Catch Authie errors

### PR DESCRIPTION
**Pull request by danquinney**

### CODE REVIEW

**Comment by adamcooke** [comment]
Merged - thanks! :smile:

**Comment by jbrooksuk** [comment]
@adamcooke how exactly are you manually merging? I'm interested to know :)

**Comment by adamcooke** [comment]
@jbrooksuk I'm glad you asked. I wrote a blog post about it back in March :) https://adamcooke.io/merging-pull-requests/

**Comment by jbrooksuk** [comment]
Nice, thank you @adamcooke. This is really useful for me!

**Pull request closed without merging**
